### ISSUE TITLE
Import Finnish Postcode Geometries

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data-postalcode-fi#1]
The file **Issue99_Postcode_Import.geojson** is now in the `whosonfirst.mapzen.com/misc` folder in the S3 bucket. This file is ready for import - it contains all current postcodes (3036 of them) mapped to new geometries. 

The data source for new postcode geometries: [Statistics Finland](http://www.stat.fi/tup/paavo/index_en.html).

WOF currently has 3,359 postalcode records for Finland, though, so ~300 of the un-mapped records will need to be deprecated. I can provide a CSV of these un-mapped records if useful.

**Comment by thisisaaronland** [comment]
![screen shot 2016-05-31 at 16 07 50](https://cloud.githubusercontent.com/assets/12658759/15693404/e42ac17c-2749-11e6-876b-2084bd581690.png)

Existing WOF records _without_ geometries that should probably be deprecated have not been teased out (or deprecated) yet.
